
version: 2

models:
  - name: stg_shopify_orders
    description: "orders data to be cleaned"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null


