# .dlt/secrets.toml (template)
[sources.shopify_dlt]
private_app_password = ""
access_token = ""

[destination.bigquery]
location = "EU"
[destination.bigquery.credentials]
project_id = ""
private_key = "/tmp/key.json"
client_email = ""
