# .dlt/secrets.toml (template)
[sources.shopify_dlt]
private_app_password = "" # will be set dynamically
access_token = "" # will be set dynamically

[destination.bigquery]
location = "EU"
[destination.bigquery.credentials]
project_id = "" # will be set dynamically
private_key = "" # will be set dynamically
client_email = "" # will be set dynamically
